### ISSUE TITLE
Simulation View

### ISSUE THREAD

**Issue by jktin12** [DerekStride/social-simulator#12]
See pull request #13 for more information

Input:
 - social user type
 - search strategy
 - social strategy
 - quantity

Format:

| Social user type | Search strategy | Social strategy | Quantity |
|-----------------------|-----------------------|---------------------|-------------|

Can add multiple of these; for example:

| Producer   | Popularity | Similarity | 30 |
|-----------------------|-----------------------|---------------------|-------------|

| Consumer | Popularity | Similarity | 120 |
|-----------------------|-----------------------|---------------------|-------------|

| Add + |
|---------|

Then will need to produce an array of hashes that will be sent to *start the simulation*

**Comment by DerekStride** [comment]
Opps, didn't mean to have that close.

We need to add some fields to configure the number of tags in a simulation. The following are some potentially useful fields I think would be useful

* Total number of tags in the simulation
* The average number of tags per user
  * The standard deviation for determining the number of tags

Also, I want to add [Twine](https://github.com/Shopify/twine) and refactor the js a bit.

**Comment by jktin12** [comment]
Okay so new branch? You deleted the `simulations-view` branch, right?

**Comment by DerekStride** [comment]
Yeah, we can use multiple branchs, one for the new fields, one for twine, etc

**Comment by DerekStride** [comment]
This view is mostly complete and working now.
