### ISSUE TITLE
Create base simulation in the controller based on params from 'New simulation' page

### ISSUE THREAD

**Issue by jktin12** [DerekStride/social-simulator#18]
We have simulation params coming in now letting us start creating users and tags.

We should create n unique tags for the simulations "tag pool". Then give users a random number of them (potentially centered on a given average).

- [ ] capture the information from the simulation table and create params hash (see first comment in #14 )
```ruby
"simulation" => {
  "users_attributes " => {
    "0" => {
      "role" => "",
      "search_strategy" => "",
      "social_strategy" => "",
      "number" => "4"
    }
  }
}
```
- [ ] Create simulation instance in controller based on these params.

**Comment by DerekStride** [comment]
This was closed by #20
